name: location_autocomplete
description: "A flutter package for location autocomplete using the Google Places API."
version: 0.0.2
homepage: https://github.com/komlan55/location_autocomplete

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  uuid: ^4.5.1

dev_dependencies:
  mockito: ^5.4.6
  build_runner: ^2.4.15
  test: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
assets:
  - assets/images/
