name: Flutter Tests
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 15 Pro'


      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get